name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Retrieve version
      run: |
        echo VERSION=$(echo ${{ github.event.head_commit.id }} | head -c 10) >> $GITHUB_ENV
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew -PappVerName=${{ env.VERSION }} assembleRelease assembleDebug
    - name: Upload built apk
      uses: actions/upload-artifact@v2
      with:
        name: snapshot
        path: |
          ${{ github.workspace }}/app/build/outputs/apk/debug/*.apk
          ${{ github.workspace }}/app/build/outputs/apk/release/*.apk
    - name: Send Package To Devloping Group
      run: |
        curl -F 'file=@${{ github.workspace }}/app/build/outputs/apk/debug/Qingxin_${{ env.VERSION }}.apk' \
        -F 'fileName=Qingxin_${{ env.VERSION }}.apk' ${{ secrets.PACKAGE_UPLOAD_URL }}
